
[functions.submit_registration]
enabled = true
verify_jwt = true
import_map = "./functions/submit_registration/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/submit_registration/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/submit_registration/*.html" ]

[functions.admin_list_team_meta]
enabled = true
verify_jwt = true
import_map = "./functions/admin_list_team_meta/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/admin_list_team_meta/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/admin_list_team_meta/*.html" ]

[functions.admin_update_team_meta]
enabled = true
verify_jwt = true
import_map = "./functions/admin_update_team_meta/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/admin_update_team_meta/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/admin_update_team_meta/*.html" ]

[functions.export_csv]
enabled = true
verify_jwt = true
import_map = "./functions/export_csv/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/export_csv/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/export_csv/*.html" ]
